import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faComment,
  faItalic,
  faUnderline,
  faStrikethrough,
  faBold,
  faGripLinesVertical,
  faFont,
  faLink,
  faImage,
  faIndent,
  faEllipsisVertical,
  faList,
  faListNumeric,
  faCaretDown,
  faCaretUp,
  faAngleRight,
  faRotateLeft,
  faRotateRight,
  faMagnifyingGlass,
  faCircle,
  faAlignLeft,
  faAlignRight,
  faAlignCenter,
  faAlignJustify,
  faMagnifyingGlassPlus,
  faTextHeight,
  faPalette,
  faTextSlash,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faComment,
  faBold,
  faItalic,
  faUnderline,
  faStrikethrough,
  faGripLinesVertical,
  faFont,
  faLink,
  faImage,
  faAlignLeft,
  faAlignRight,
  faAlignCenter,
  faAlignJustify,
  faIndent,
  faEllipsisVertical,
  faList,
  faListNumeric,
  faCaretDown,
  faCaretUp,
  faAngleRight,
  faRotateLeft,
  faRotateRight,
  faMagnifyingGlass,
  faCircle,
  faMagnifyingGlassPlus,
  faFont,
  faTextHeight,
  faPalette,
  faTextSlash,
);

export default library;
